### ISSUE TITLE
Custom AttackDamage of the swords in the shop

### ISSUE THREAD

**Issue by Gr3gory** [pronze/SBAHypixelify#121]
I need to set the Attack Damage of the swords sold in the shop. I need this but with correct YAML configuration
```
- stack: IRON_SWORD;1
    meta:
      ==: ItemMeta
      AttackDamage(on_hand=5)
    price: 7 of gold
    row: 4
    column: 2
```

**Comment by Gr3gory** [comment]
I have found this solution to put in store.yml file in the SBAHYpixelify folder, under - stack
```
meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: Some name
    loc-name: some localized name
    lore:
   - a lote
    - s second lore
    - and a third
    custom-model-data: 1
    enchants:
      DAMAGE_ALL: 100
      LOOT_BONUS_MOBS: 2
    attribute-modifiers:
      GENERIC_ATTACK_SPEED:
      - ==: org.bukkit.attribute.AttributeModifier
        amount: 10.0
        name: a name
        slot: HAND
        uuid: eb7ae7aa-02ea-430a-ba0e-a7aae4165f4b
        operation: 1
      GENERIC_ARMOR:
      - ==: org.bukkit.attribute.AttributeModifier
        amount: 10.0
        name: a name
        uuid: b474ca00-e59f-4dbe-8f75-439891ec75e4
        operation: 1
```
